const qs = (s) => document.querySelector(s);
const pageParams = new URLSearchParams(location.search);
const invite = pageParams.get('invite') || '';
const urlToken = pageParams.get('token') || '';
const API_BASE = String(window.BABY_NOTE_API_BASE || '').replace(/\/$/, '');
let token = urlToken || (invite ? '' : localStorage.getItem('newborn.v2.token') || '');
if (urlToken) localStorage.setItem('newborn.v2.token', urlToken);
if (invite) localStorage.removeItem('newborn.v2.token');
const canEdit = false;
const DEFAULT_ACTIONS = [
  { key:'feed', label:'喝奶', icon:'feed', tone:'lilac', enabled:true, builtIn:true },
  { key:'urine', label:'小便', icon:'urine', tone:'sky', enabled:true, builtIn:true },
  { key:'stool', label:'大便', icon:'stool', tone:'amber', enabled:true, builtIn:true },
  { key:'diaper', label:'换尿布', icon:'diaper', tone:'rose', enabled:true, builtIn:true },
  { key:'ad', label:'吃 AD', icon:'ad', tone:'sun', enabled:true, builtIn:true }
];
const ICONS = {
  feed:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 4h6M10 4v2m4-2v2M8 7h8l1 12H7L8 7Zm2 4h4"/></svg>',
  urine:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3s5 5.1 5 9a5 5 0 1 1-10 0c0-3.9 5-9 5-9Z"/></svg>',
  stool:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 17a3 3 0 1 1 0-6 4 4 0 1 1 7.2-2.4A3.5 3.5 0 1 1 16 17H8Z"/></svg>',
  diaper:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 6c2.3 1.2 4.6 1.8 7 1.8S16.7 7.2 19 6v8.2c-1.6 2.4-3.9 3.8-7 3.8s-5.4-1.4-7-3.8V6Z"/><path d="M5 6c1.2 2 2.5 3 4.2 3.5M19 6c-1.2 2-2.5 3-4.2 3.5"/></svg>',
  ad:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>'
};
const iconMarkup = (action) => ICONS[action?.key] || (ICONS[action?.icon] || action?.icon || '•');
let state = { baby: { name: '小宝' }, actions: structuredClone(DEFAULT_ACTIONS), events: [] };
let session = { role: 'anonymous', canEdit };
let verificationId = '';
let codeCountdown = 0;
let codeTimer;
const pendingKey = 'newborn.v2.pending';
const pending = () => JSON.parse(localStorage.getItem(pendingKey) || '[]');
const savePending = (ops) => localStorage.setItem(pendingKey, JSON.stringify(ops));
const localKey = 'newborn.v2.state';
const saveLocal = () => localStorage.setItem(localKey, JSON.stringify(state));
const fmtTime = (iso) => new Intl.DateTimeFormat('zh-CN', { hour:'2-digit', minute:'2-digit', hour12:false }).format(new Date(iso));
const fmtDate = (iso) => new Intl.DateTimeFormat('zh-CN', { month:'long', day:'numeric', weekday:'short' }).format(new Date(iso));
const dayKey = (iso) => new Intl.DateTimeFormat('zh-CN', { year:'numeric', month:'2-digit', day:'2-digit' }).format(new Date(iso));
const nowLocalInput = () => { const d = new Date(Date.now() - new Date().getTimezoneOffset()*60000); return d.toISOString().slice(0,16); };
const actionFor = (key) => state.actions.find((a) => a.key === key) || { key, label:'动作', icon:'•', tone:'lilac' };
function toast(message) { const el = qs('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.t); toast.t = setTimeout(() => el.classList.remove('show'), 2200); }
function setSync(label, tone='') { qs('#sync-label').textContent = label; qs('#sync-dot').className = `sync-dot ${tone}`; }
async function api(path, options={}) { const headers = { ...(options.body ? {'content-type':'application/json'} : {}), 'x-access-token': token, ...(token ? {Authorization: `Bearer ${token}`} : {}), ...(options.headers || {}) }; const res = await fetch(API_BASE + path, {...options, headers}); if (!res.ok) throw new Error((await res.json().catch(() => ({}))).error || `HTTP ${res.status}`); return res.json(); }
function applyLocal(op) { if (op.type === 'add-event' && !state.events.some(e=>e.id===op.event.id)) state.events.push(op.event); if (op.type === 'update-event') { const i=state.events.findIndex(e=>e.id===op.event.id); if(i>=0) state.events[i]={...state.events[i],...op.event}; } if (op.type === 'delete-event') state.events=state.events.filter(e=>e.id!==op.id); if (op.type === 'add-action' && !state.actions.some(a=>a.key===op.action.key)) state.actions.push(op.action); if (op.type === 'update-baby' && op.baby?.name) state.baby={...state.baby,name:op.baby.name}; saveLocal(); render(); }
function queue(op) { const ops = pending(); ops.push(op); savePending(ops); applyLocal(op); trySync(); }
function renderActions() { const host = qs('#quick-actions'); host.innerHTML = ''; state.actions.filter(a=>a.enabled!==false).forEach((a) => { const button = document.createElement('button'); button.className = `quick-card ${a.tone || 'lilac'}`; button.innerHTML = `<span class="quick-icon">${iconMarkup(a)}</span><span class="quick-label">${a.label}</span><span class="quick-last">${lastFor(a.key) || '　'}</span>`; button.onclick = () => quickLog(a); host.appendChild(button); }); if (session.canEdit) { const add = document.createElement('button'); add.className='quick-card add'; add.innerHTML='<span class="quick-icon">＋</span><span class="quick-label">自定义</span><span class="quick-last">新增动作</span>'; add.onclick=()=>qs('#custom-dialog').showModal(); host.appendChild(add); } }
function lastFor(key) { const e = [...state.events].filter(e=>e.actionKey===key).sort((a,b)=>new Date(b.at)-new Date(a.at))[0]; return e ? fmtTime(e.at) : ''; }
function renderTimeline() { const host=qs('#timeline'); const events=[...state.events].sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,60); if(!events.length){host.innerHTML='<div class="empty">还没有记录<br>轻触上方动作，就会从现在开始留下时间线</div>';return;} let html='', prev=''; for(const e of events){ const d=dayKey(e.at); if(d!==prev){html+=`<div class="day-heading"><span>${fmtDate(e.at)}</span></div>`;prev=d;} const a=actionFor(e.actionKey); const detail=[e.amountMl?`${e.amountMl} ml`:'',e.note].filter(Boolean).join(' · ') || '已记录'; html+=`<div class="event-row"><span class="event-icon ${a.tone||''}">${iconMarkup(a)}</span><div class="event-main"><div class="event-title">${a.label}</div><div class="event-meta">${detail}</div></div><div class="event-actions"><span class="event-time">${fmtTime(e.at)}</span>${session.canEdit?`<button class="edit-btn" data-id="${e.id}" aria-label="编辑">✎</button>`:''}</div></div>`;} host.innerHTML=html; host.querySelectorAll('.edit-btn').forEach(b=>b.onclick=()=>openEdit(b.dataset.id)); }
function updateDayMark(){ const bars=[...document.querySelectorAll('.day-mark span')]; const today=dayKey(new Date().toISOString()); const todayEvents=state.events.filter(e=>dayKey(e.at)===today); const count=qs('#today-count'); if(count) count.textContent=todayEvents.length?`${todayEvents.length} 次照护记录`:'从第一条记录开始'; if(!bars.length)return; const counts=[0,0,0,0,0]; todayEvents.forEach(e=>{ const h=new Date(e.at).getHours(); const bucket=h<5?0:h<10?1:h<15?2:h<20?3:4; counts[bucket]++; }); const max=Math.max(...counts,1); bars.forEach((bar,i)=>{ const height=counts[i]?`${Math.round(34+(counts[i]/max)*58)}%`:'24%'; bar.style.height=height; bar.style.opacity=counts[i]?'1':'.35'; }); }
function updateDailyReport(){ const today=dayKey(new Date().toISOString()); const events=state.events.filter(e=>dayKey(e.at)===today); const count=(key)=>events.filter(e=>e.actionKey===key).length; const known=count('feed')+count('diaper')+count('ad'); const values={ '#report-total':events.length, '#report-feed':count('feed'), '#report-diaper':count('diaper'), '#report-ad':count('ad'), '#report-care':Math.max(0,events.length-known) }; Object.entries(values).forEach(([selector,value])=>{const el=qs(selector);if(el)el.textContent=String(value);}); const max=Math.max(events.length,1); document.querySelectorAll('.report-row[data-report-key]').forEach((row)=>{ const key=row.dataset.reportKey; const value=key==='care'?Math.max(0,events.length-known):count(key); const bar=row.querySelector('.report-rule i'); if(bar) bar.style.width=`${value?Math.max(10,Math.round(value/max*100)):0}%`; }); const pulse=[...document.querySelectorAll('.report-pulse i')]; pulse.forEach((bar,i)=>{ const value=events.filter(e=>{const hour=new Date(e.at).getHours(); return Math.floor(hour/3)===i;}).length; bar.style.height=value?`${Math.min(18,5+value*4)}px`:'5px'; bar.style.opacity=value?'1':'.42'; }); const caption=qs('#report-caption'); if(caption) caption.textContent=events.length?'只统计今天的记录':'等待第一条记录'; }
function render(){ qs('#baby-name').textContent=state.baby?.name||'小宝'; const roleLabels={owner:'主账号',editor:'可编辑',viewer:'只读查看',guest:'待加入',anonymous:'未登录'}; qs('#role-pill').textContent=roleLabels[session.role]||'未登录'; const login=qs('#phone-login-btn'); if(login) login.style.display=session.authenticated?'none':'inline-flex'; ['edit-baby-btn','share-btn'].forEach(id=>{const el=qs(`#${id}`);if(el)el.style.display=(id==='share-btn'?session.canShare:session.canEdit)?'flex':'none';}); renderActions(); renderTimeline(); updateDayMark(); updateDailyReport(); }
async function quickLog(a){ if(!session.canEdit){toast('当前是只读查看模式');return;} if(a.key==='feed' && !localStorage.getItem('newborn.v2.lastAmount')){ openEdit(null,'首次喝奶记录',a.key); qs('#edit-amount').required=true; return; } const amount=a.key==='feed'?Number(localStorage.getItem('newborn.v2.lastAmount')||0)||null:null; const event={id:crypto.randomUUID(),actionKey:a.key,at:new Date().toISOString(),amountMl:amount,note:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; queue({type:'add-event',event}); toast(amount?`已记录喝奶 ${amount} ml`:`已记录${a.label}`); }
function openEdit(id,title='编辑记录',actionKey='feed'){ const e=id?state.events.find(x=>x.id===id):null; qs('#record-dialog-title').textContent=title; qs('#edit-id').value=e?.id||''; qs('#edit-action').innerHTML=state.actions.map(a=>`<option value="${a.key}">${a.icon} ${a.label}</option>`).join(''); qs('#edit-action').value=e?.actionKey||actionKey; qs('#edit-at').value=e?new Date(new Date(e.at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):nowLocalInput(); qs('#edit-amount').value=e?.amountMl||''; qs('#edit-note').value=e?.note||''; qs('#edit-amount').required=false; qs('#delete-record').style.visibility=e?'visible':'hidden'; updateAmountVisibility(); qs('#record-dialog').showModal(); }
function updateAmountVisibility(){ const feed=qs('#edit-action').value==='feed'; qs('#amount-field').style.display=feed?'block':'none'; }
qs('#edit-action').onchange=updateAmountVisibility;
qs('#record-form').onsubmit=(ev)=>{ev.preventDefault(); const id=qs('#edit-id').value; const at=new Date(qs('#edit-at').value).toISOString(); const actionKey=qs('#edit-action').value; const amount=qs('#edit-amount').value; const event={id:id||crypto.randomUUID(),actionKey,at,amountMl:amount?Number(amount):null,note:qs('#edit-note').value.trim(),updatedAt:new Date().toISOString(),createdAt:id?(state.events.find(e=>e.id===id)?.createdAt||new Date().toISOString()):new Date().toISOString()}; if(event.actionKey==='feed'&&event.amountMl)localStorage.setItem('newborn.v2.lastAmount',String(event.amountMl)); queue({type:id?'update-event':'add-event',...(id?{event}:{event})}); qs('#record-dialog').close(); toast(id?'已更新记录':'已新增记录'); };
qs('#delete-record').onclick=()=>{const id=qs('#edit-id').value;if(id&&confirm('确认删除这条记录？')){queue({type:'delete-event',id});qs('#record-dialog').close();toast('已删除');}};
qs('#add-record-btn').onclick=()=>{if(session.canEdit)openEdit(null,'补记记录','feed');else toast('当前是只读查看模式');};
qs('#custom-form').onsubmit=(ev)=>{ev.preventDefault();const label=qs('#custom-label').value.trim();const icon=qs('#custom-icon').value.trim()||'•';const action={key:`custom-${crypto.randomUUID().slice(0,8)}`,label,icon,tone:'lilac',enabled:true};queue({type:'add-action',action});qs('#custom-dialog').close();qs('#custom-form').reset();toast('已添加自定义动作');};
qs('#settings-btn').onclick=()=>qs('#settings-dialog').showModal(); qs('#add-custom-btn').onclick=()=>{qs('#settings-dialog').close();qs('#custom-dialog').showModal();}; qs('#edit-baby-btn').onclick=()=>{qs('#settings-dialog').close();qs('#baby-name-input').value=state.baby?.name||'';qs('#baby-dialog').showModal();}; qs('#baby-form').onsubmit=(ev)=>{ev.preventDefault();const name=qs('#baby-name-input').value.trim();if(!name)return;queue({type:'update-baby',baby:{name}});qs('#baby-dialog').close();toast(`已更新宝宝名字为「${name}」`);};
qs('#share-btn').onclick=async()=>{try{const links=await api('/api/share');qs('#edit-share-link').textContent=links.editUrl;qs('#view-share-link').textContent=links.viewUrl;qs('#share-dialog').showModal();}catch{toast('当前环境暂时无法生成链接');}}; document.querySelectorAll('.copy-share').forEach((button)=>button.onclick=async()=>{const text=qs(`#${button.dataset.target}`).textContent;try{await navigator.clipboard?.writeText(text);toast('链接已复制');}catch{toast('请长按链接复制');}});
function normalizePhone(value){ return String(value || '').replace(/\D/g,'').slice(0,11); }
function setLoginHint(message, tone=''){ const el=qs('#phone-login-hint'); if(el){ el.textContent=message; el.className='login-hint '+tone; } }
function openPhoneLogin(){ if(session.authenticated){ toast('当前已登录'); return; } setLoginHint('验证码有效期有限，请在收到后尽快填写'); qs('#phone-login-dialog').showModal(); setTimeout(()=>qs('#phone-input').focus(), 0); }
function startCodeCountdown(){ codeCountdown=60; const button=qs('#send-code-btn'); button.disabled=true; button.textContent=codeCountdown+'s 后重发'; clearInterval(codeTimer); codeTimer=setInterval(()=>{ codeCountdown-=1; if(codeCountdown<=0){ clearInterval(codeTimer); button.disabled=false; button.textContent='重新获取'; } else button.textContent=codeCountdown+'s 后重发'; },1000); }
qs('#phone-login-btn').onclick=openPhoneLogin;
qs('#phone-login-close').onclick=()=>qs('#phone-login-dialog').close();
qs('#send-code-btn').onclick=async()=>{ const phone=normalizePhone(qs('#phone-input').value); qs('#phone-input').value=phone; if(!/^1\d{10}$/.test(phone)){ setLoginHint('请输入有效的 11 位中国大陆手机号','error'); qs('#phone-input').focus(); return; } const button=qs('#send-code-btn'); button.disabled=true; button.textContent='发送中…'; setLoginHint('正在发送验证码…'); try{ const result=await api('/api/auth/phone/send',{method:'POST',body:JSON.stringify({phone})}); verificationId=result.verificationId || ''; if(!verificationId) throw new Error('服务端没有返回验证信息'); startCodeCountdown(); setLoginHint('验证码已发送，请查收短信'); qs('#phone-code-input').focus(); }catch(error){ button.disabled=false; button.textContent='获取验证码'; setLoginHint(error.message || '验证码发送失败，请稍后重试','error'); } };
qs('#phone-login-form').onsubmit=async(ev)=>{ ev.preventDefault(); const phone=normalizePhone(qs('#phone-input').value); const code=String(qs('#phone-code-input').value || '').trim(); if(!/^1\d{10}$/.test(phone)){ setLoginHint('请输入有效的 11 位中国大陆手机号','error'); return; } if(!/^\d{4,8}$/.test(code)){ setLoginHint('请输入短信中的数字验证码','error'); return; } if(!verificationId){ setLoginHint('请先获取验证码','error'); return; } const submit=qs('#phone-submit-btn'); submit.disabled=true; submit.textContent='登录中…'; setLoginHint('正在验证手机号…'); try{ const loginResult=await api('/api/auth/phone/login',{method:'POST',body:JSON.stringify({phone,code,verificationId})}); if(loginResult.sessionToken){ token=loginResult.sessionToken; localStorage.setItem('newborn.v2.token',token); } verificationId=''; clearInterval(codeTimer); qs('#phone-login-dialog').close(); session=await api('/api/session'); if(invite) await acceptPendingInvite(); render(); if(session.role==='guest'){setSync('待加入 · 请使用共享链接','warn');} else {setSync('正在同步…'); await trySync();} toast('手机号登录成功'); }catch(error){ setLoginHint(error.message || '登录失败，请检查验证码','error'); }finally{ submit.disabled=false; submit.textContent='登录 / 注册'; } };
qs('#export-btn').onclick=async()=>{ try{ const response=await fetch(API_BASE + '/api/export',{headers:{'x-access-token':token,...(token ? {Authorization:`Bearer ${token}`} : {})}}); if(!response.ok){ const data=await response.json().catch(()=>({})); throw new Error(data.error||'云端数据下载失败'); } const blob=await response.blob(); const disposition=response.headers.get('content-disposition')||''; const match=disposition.match(/filename="([^"]+)"/); const filename=match?.[1]||('baby-note-cloud-'+new Date().toISOString().slice(0,10)+'.json'); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=filename; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); toast('已下载云端完整数据'); }catch(error){ toast(error.message||'云端数据下载失败'); } };
qs('#sync-now').onclick=()=>trySync(true);
async function trySync(force=false){ if(!navigator.onLine){setSync('离线 · 待同步','warn');return;} try{ if(session.canEdit&&pending().length){setSync('正在同步…');await api('/api/sync',{method:'POST',body:JSON.stringify({ops:pending()})});savePending([]);} const remote=await api('/api/state'); state=remote; saveLocal(); render(); if(session.cloudStorageConfigured){ setSync('已同步 '+fmtTime(new Date().toISOString()),'ok'); } else { setSync('待同步 · 云存储未配置','warn'); } if(force)toast(session.cloudStorageConfigured?'已完成云端同步':'当前仅保存到本机'); }catch{setSync('待同步 · 稍后重试','warn');} }
async function acceptPendingInvite(){ if(!invite||!session.authenticated)return false; try{ const result=await api('/api/share/invite/accept',{method:'POST',body:JSON.stringify({invite})}); const next=new URL(location.href); next.searchParams.delete('invite'); history.replaceState({},'',next.pathname+(next.search||'')); session=await api('/api/session'); toast(result.role==='editor'?'已加入可编辑共享记录':'已加入只读共享记录'); return true; }catch(error){ toast(error.message||'共享链接暂时无法使用'); return false; } }
async function boot(){ try{const s=await api('/api/session');session=s; const cached=JSON.parse(localStorage.getItem(localKey)||'null'); if(cached && s.hasAccess)state=cached; render(); if(s.role==='anonymous'){setSync(invite?'请先登录后加入共享记录':'请先登录','warn'); if(invite)setTimeout(openPhoneLogin,220); return;} if(invite) await acceptPendingInvite(); if(session.role==='guest'){setSync('待加入 · 请使用共享链接','warn');return;} await trySync(); }catch{ const cached=JSON.parse(localStorage.getItem(localKey)||'null'); if(cached)state={...state,...cached,actions:cached.actions?.length?cached.actions:structuredClone(DEFAULT_ACTIONS)}; render(); setSync('离线 · 本机记录','warn'); } }
setInterval(()=>{const d=new Date();qs('#live-clock').textContent=new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}).format(d);qs('#today-label').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(d);},1000); setInterval(()=>trySync(),30000); window.addEventListener('online',()=>trySync());
if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{}); boot();
